/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.vrany.chatbot;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 * Panel pro nastaveni vlastnosti chatu
 *
 * @author michal
 */
public class ChatPanel extends javax.swing.JPanel {

    Chat chat;

    /**
     * Creates new form ChatPanel
     */
    public ChatPanel() {
        initComponents();
        chat = new Chat();
    }

    public void setScreenDimension(Dimension screenDimension) {
        xpos.setMaximum(screenDimension.width);
        ypos.setMaximum(screenDimension.height);

    }

    public Dimension getScreenDimension() {
        return new Dimension(xpos.getMaximum(), ypos.getMaximum());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        backRed = new javax.swing.JSlider();
        backGreen = new javax.swing.JSlider();
        backBlue = new javax.swing.JSlider();
        foreTransparency = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        width = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        height = new javax.swing.JSlider();
        backTransparency = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        xpos = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        ypos = new javax.swing.JSlider();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        sysRed = new javax.swing.JSlider();
        sysGreen = new javax.swing.JSlider();
        sysBlue = new javax.swing.JSlider();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        fontRed = new javax.swing.JSlider();
        fontGreen = new javax.swing.JSlider();
        fontBlue = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        preview = new javax.swing.JLabel();
        chatVisible = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        catchRed = new javax.swing.JSlider();
        catchGreen = new javax.swing.JSlider();
        catchBlue = new javax.swing.JSlider();

        jLabel10.setText("Background color");

        jButton4.setText("Set");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        backRed.setMaximum(255);
        backRed.setPreferredSize(new java.awt.Dimension(60, 23));
        backRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                backRedbackColorChanged(evt);
            }
        });
        jPanel2.add(backRed);

        backGreen.setMaximum(255);
        backGreen.setPreferredSize(new java.awt.Dimension(60, 23));
        backGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                backGreenbackColorChanged(evt);
            }
        });
        jPanel2.add(backGreen);

        backBlue.setMaximum(255);
        backBlue.setPreferredSize(new java.awt.Dimension(60, 23));
        backBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                backBluebackColorChanged(evt);
            }
        });
        jPanel2.add(backBlue);

        foreTransparency.setMaximum(255);
        foreTransparency.setValue(128);
        foreTransparency.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                foreTransparencyStateChanged(evt);
            }
        });

        jLabel4.setText("Foreground chat transparency");

        jLabel5.setText("Width");

        width.setMaximum(800);
        width.setMinimum(200);
        width.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                widthStateChanged(evt);
            }
        });

        jLabel6.setText("Height");

        height.setMaximum(600);
        height.setMinimum(100);
        height.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heightStateChanged(evt);
            }
        });

        backTransparency.setMaximum(255);
        backTransparency.setValue(128);
        backTransparency.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                backTransparencyStateChanged(evt);
            }
        });

        jLabel1.setText("Background chat transparency");

        jLabel2.setText("X position");

        xpos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                xposStateChanged(evt);
            }
        });

        jLabel3.setText("Y position");

        ypos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                yposStateChanged(evt);
            }
        });

        jLabel12.setText("System text color");

        jButton6.setText("Set");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);

        sysRed.setMaximum(255);
        sysRed.setPreferredSize(new java.awt.Dimension(60, 23));
        sysRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sysRedbackColorChanged(evt);
            }
        });
        jPanel4.add(sysRed);

        sysGreen.setMaximum(255);
        sysGreen.setPreferredSize(new java.awt.Dimension(60, 23));
        sysGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sysGreenbackColorChanged(evt);
            }
        });
        jPanel4.add(sysGreen);

        sysBlue.setMaximum(255);
        sysBlue.setPreferredSize(new java.awt.Dimension(60, 23));
        sysBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sysBluebackColorChanged(evt);
            }
        });
        jPanel4.add(sysBlue);

        jLabel13.setText("Font text color");

        jButton7.setText("Set");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);

        fontRed.setMaximum(255);
        fontRed.setPreferredSize(new java.awt.Dimension(60, 23));
        fontRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fontRedbackColorChanged(evt);
            }
        });
        jPanel5.add(fontRed);

        fontGreen.setMaximum(255);
        fontGreen.setPreferredSize(new java.awt.Dimension(60, 23));
        fontGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fontGreenbackColorChanged(evt);
            }
        });
        jPanel5.add(fontGreen);

        fontBlue.setMaximum(255);
        fontBlue.setPreferredSize(new java.awt.Dimension(60, 23));
        fontBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fontBluebackColorChanged(evt);
            }
        });
        jPanel5.add(fontBlue);

        jLabel7.setText("Select font:");

        jButton1.setText("Choose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        preview.setBackground(new java.awt.Color(255, 255, 255));
        preview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preview.setText("PREVIEW");
        preview.setOpaque(true);

        chatVisible.setText("Chat visible?");
        chatVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatVisibleActionPerformed(evt);
            }
        });

        jLabel14.setText("Catch phrases font color");

        jButton8.setText("Set");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8);

        catchRed.setMaximum(255);
        catchRed.setPreferredSize(new java.awt.Dimension(60, 23));
        catchRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                catchRedbackColorChanged(evt);
            }
        });
        jPanel6.add(catchRed);

        catchGreen.setMaximum(255);
        catchGreen.setPreferredSize(new java.awt.Dimension(60, 23));
        catchGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                catchGreenbackColorChanged(evt);
            }
        });
        jPanel6.add(catchGreen);

        catchBlue.setMaximum(255);
        catchBlue.setPreferredSize(new java.awt.Dimension(60, 23));
        catchBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                catchBluebackColorChanged(evt);
            }
        });
        jPanel6.add(catchBlue);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backTransparency, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xpos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ypos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(foreTransparency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(width, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(height, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(preview, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chatVisible))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(preview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(5, 5, 5)))
                            .addComponent(chatVisible))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backTransparency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foreTransparency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xpos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ypos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Color color = new Color(backRed.getValue(), backGreen.getValue(), backBlue.getValue());
        if ((color = JColorChooser.showDialog(this, "Choose color directly", color)) != null) {
            backRed.setValue(color.getRed());
            backGreen.setValue(color.getGreen());
            backBlue.setValue(color.getBlue());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void backRedbackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_backRedbackColorChanged
        Color color = new Color(backRed.getValue(), backGreen.getValue(), backBlue.getValue());
        chat.setBackground(color);
    }//GEN-LAST:event_backRedbackColorChanged

    private void backGreenbackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_backGreenbackColorChanged
        Color color = new Color(backRed.getValue(), backGreen.getValue(), backBlue.getValue());
        chat.setBackground(color);
    }//GEN-LAST:event_backGreenbackColorChanged

    private void backBluebackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_backBluebackColorChanged
        Color color = new Color(backRed.getValue(), backGreen.getValue(), backBlue.getValue());
        chat.setBackground(color);
    }//GEN-LAST:event_backBluebackColorChanged

    private void foreTransparencyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_foreTransparencyStateChanged
        chat.setForeTransparent(foreTransparency.getValue());
    }//GEN-LAST:event_foreTransparencyStateChanged

    private void widthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_widthStateChanged
        chat.setWidth(width.getValue());
    }//GEN-LAST:event_widthStateChanged

    private void heightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_heightStateChanged
        chat.setHeight(height.getValue());
    }//GEN-LAST:event_heightStateChanged

    private void backTransparencyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_backTransparencyStateChanged
        chat.setBackTransparent(backTransparency.getValue());
    }//GEN-LAST:event_backTransparencyStateChanged

    private void xposStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_xposStateChanged
        adjustLocation();
    }//GEN-LAST:event_xposStateChanged

    private void yposStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yposStateChanged
        adjustLocation();
    }//GEN-LAST:event_yposStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Color color = new Color(sysRed.getValue(), sysGreen.getValue(), sysBlue.getValue());
        if ((color = JColorChooser.showDialog(this, "Choose color directly", color)) != null) {
            sysRed.setValue(color.getRed());
            sysGreen.setValue(color.getGreen());
            sysBlue.setValue(color.getBlue());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void sysRedbackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sysRedbackColorChanged
        setSystemColor();
    }//GEN-LAST:event_sysRedbackColorChanged


    private void sysGreenbackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sysGreenbackColorChanged
        Color color = new Color(sysRed.getValue(), sysGreen.getValue(), sysBlue.getValue());
        chat.setSystemColor(color);
        chat.repaint();
    }//GEN-LAST:event_sysGreenbackColorChanged

    private void sysBluebackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sysBluebackColorChanged
        Color color = new Color(sysRed.getValue(), sysGreen.getValue(), sysBlue.getValue());
        chat.setSystemColor(color);
        chat.repaint();
    }//GEN-LAST:event_sysBluebackColorChanged

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Color color = new Color(fontRed.getValue(), fontGreen.getValue(), fontBlue.getValue());
        if ((color = JColorChooser.showDialog(this, "Choose color directly", color)) != null) {
            fontRed.setValue(color.getRed());
            fontGreen.setValue(color.getGreen());
            fontBlue.setValue(color.getBlue());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void fontRedbackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fontRedbackColorChanged
        setFontColor();
    }//GEN-LAST:event_fontRedbackColorChanged

    private void fontGreenbackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fontGreenbackColorChanged
        setFontColor();
    }//GEN-LAST:event_fontGreenbackColorChanged

    private void fontBluebackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fontBluebackColorChanged
        setFontColor();
    }//GEN-LAST:event_fontBluebackColorChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FontChooserDialog dlg = new FontChooserDialog(JOptionPane.getFrameForComponent(this), true);
        dlg.setValue(chat.ps.messageFont);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
        if (dlg.okPressed) {
            chat.setMessageFont(dlg.getValue());
            preview.setFont(chat.ps.messageFont);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chatVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatVisibleActionPerformed
        chat.setVisible(chatVisible.isSelected());
    }//GEN-LAST:event_chatVisibleActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Color color = new Color(catchRed.getValue(), catchGreen.getValue(), catchBlue.getValue());
        if ((color = JColorChooser.showDialog(this, "Choose color directly", color)) != null) {
            catchRed.setValue(color.getRed());
            catchGreen.setValue(color.getGreen());
            catchBlue.setValue(color.getBlue());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void catchRedbackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_catchRedbackColorChanged
        setCatchColor();
    }//GEN-LAST:event_catchRedbackColorChanged

    private void catchGreenbackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_catchGreenbackColorChanged
        setCatchColor();
    }//GEN-LAST:event_catchGreenbackColorChanged

    private void catchBluebackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_catchBluebackColorChanged
        setCatchColor();
    }//GEN-LAST:event_catchBluebackColorChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider backBlue;
    private javax.swing.JSlider backGreen;
    private javax.swing.JSlider backRed;
    private javax.swing.JSlider backTransparency;
    private javax.swing.JSlider catchBlue;
    private javax.swing.JSlider catchGreen;
    private javax.swing.JSlider catchRed;
    private javax.swing.JCheckBox chatVisible;
    private javax.swing.JSlider fontBlue;
    private javax.swing.JSlider fontGreen;
    private javax.swing.JSlider fontRed;
    private javax.swing.JSlider foreTransparency;
    private javax.swing.JSlider height;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel preview;
    private javax.swing.JSlider sysBlue;
    private javax.swing.JSlider sysGreen;
    private javax.swing.JSlider sysRed;
    private javax.swing.JSlider width;
    private javax.swing.JSlider xpos;
    private javax.swing.JSlider ypos;
    // End of variables declaration//GEN-END:variables

    private void adjustLocation() {
        if (chat != null) {
            chat.setLocation(xpos.getValue(), ypos.getValue());
        }
    }

    void loadSettings(IniFile settings) {
        String inp;
        inp = settings.getKeyValue("Chat", "backTransparency", "128");
        try {
            backTransparency.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("Chat", "foreTransparency", "128");
        try {
            foreTransparency.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("Chat", "xpos", "1600");
        try {
            xpos.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("Chat", "ypos", "200");
        try {
            ypos.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("Chat", "width", "400");
        try {
            width.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("Chat", "height", "300");
        try {
            height.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("Chat", "backRed", "192");
        try {
            backRed.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("Chat", "backGreen", "192");
        try {
            backGreen.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("Chat", "backBlue", "192");
        try {
            backBlue.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("Chat", "sysRed", "255");
        try {
            sysRed.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("Chat", "sysGreen", "255");
        try {
            sysGreen.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("Chat", "sysBlue", "0");
        try {
            sysBlue.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("Chat", "fontRed", "255");
        try {
            fontRed.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("Chat", "fontGreen", "255");
        try {
            fontGreen.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("Chat", "fontBlue", "0");
        try {
            fontBlue.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        String fontFamily = settings.getKeyValue("Chat", "fontFamily", "Tahoma");
        int style = Font.PLAIN;
        inp = settings.getKeyValue("Chat", "fontStyle", "0");
        try {
            style = Integer.parseInt(inp);
        } catch (NumberFormatException ex) {
        }
        int size = 11;
        inp = settings.getKeyValue("Chat", "fontSize", "11");
        try {
            size = Integer.parseInt(inp);
        } catch (NumberFormatException ex) {
        }
        chat.setMessageFont(new Font(fontFamily, style, size));
        preview.setFont(chat.ps.messageFont);
        inp = settings.getKeyValue("Chat", "chatVisible", "true");
        chatVisible.setSelected(Boolean.parseBoolean(inp));
        chat.setVisible(chatVisible.isSelected());
        inp = settings.getKeyValue("Chat", "catchRed", "255");
        try {
            catchRed.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("Chat", "catchGreen", "255");
        try {
            catchGreen.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("Chat", "catchBlue", "0");
        try {
            catchBlue.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
    }

    public void onJoin(TwitchChatEvent evt, boolean hosted) {
        chat.addMessage(hosted, false, null, "HELLO USER " + evt.user);
    }

    public void onMessage(boolean hosted, boolean catchPhrase, User user, String message) {
        chat.addMessage(hosted, catchPhrase, user, message);
    }

    public void onClose(TwitchChatEvent evt, boolean hosted) {
        chat.addMessage(hosted, false, null, "CLOSED");
    }

    void saveSettings(IniFile settings) {
        settings.setValue("Chat", "backTransparency", String.valueOf(backTransparency.getValue()));
        settings.setValue("Chat", "foreTransparency", String.valueOf(foreTransparency.getValue()));
        settings.setValue("Chat", "xpos", String.valueOf(chat.getX()));
        settings.setValue("Chat", "ypos", String.valueOf(chat.getY()));
        settings.setValue("Chat", "width", String.valueOf(chat.getWidth()));
        settings.setValue("Chat", "height", String.valueOf(chat.getHeight()));
        settings.setValue("Chat", "backRed", String.valueOf(backRed.getValue()));
        settings.setValue("Chat", "backGreen", String.valueOf(backGreen.getValue()));
        settings.setValue("Chat", "backBlue", String.valueOf(backBlue.getValue()));
        settings.setValue("Chat", "sysRed", String.valueOf(sysRed.getValue()));
        settings.setValue("Chat", "sysGreen", String.valueOf(sysGreen.getValue()));
        settings.setValue("Chat", "sysBlue", String.valueOf(sysBlue.getValue()));
        settings.setValue("Chat", "fontRed", String.valueOf(fontRed.getValue()));
        settings.setValue("Chat", "fontGreen", String.valueOf(fontGreen.getValue()));
        settings.setValue("Chat", "fontBlue", String.valueOf(fontBlue.getValue()));
        settings.setValue("Chat", "fontFamily", chat.ps.messageFont.getFamily());
        settings.setValue("Chat", "fontStyle", String.valueOf(chat.ps.messageFont.getStyle()));
        settings.setValue("Chat", "fontSize", String.valueOf(chat.ps.messageFont.getSize()));
        settings.setValue("Chat", "chatVisible", String.valueOf(chatVisible.isSelected()));
        settings.setValue("Chat", "catchRed", String.valueOf(catchRed.getValue()));
        settings.setValue("Chat", "catchGreen", String.valueOf(catchGreen.getValue()));
        settings.setValue("Chat", "catchBlue", String.valueOf(catchBlue.getValue()));
    }

    Color getSystemColor() {
        return chat.ps.systemColor;
    }

    private void setSystemColor() {
        Color color = new Color(sysRed.getValue(), sysGreen.getValue(), sysBlue.getValue());
        chat.setSystemColor(color);
        chat.repaint();
    }

    private void setCatchColor() {
        Color color = new Color(catchRed.getValue(), catchGreen.getValue(), catchBlue.getValue());
        chat.setCatchColor(color);
        chat.repaint();
    }

    private void setFontColor() {
        Color color = new Color(fontRed.getValue(), fontGreen.getValue(), fontBlue.getValue());
        chat.setFontColor(color);
        chat.repaint();
    }
}
