/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.vrany.chatbot;

import java.awt.Font;
import java.awt.GraphicsEnvironment;
import javax.swing.AbstractListModel;

/**
 *
 * @author michal
 */
public class FontChooser extends javax.swing.JPanel {

    final String[] fontFamilyNames;
    final String[] fontStylesNames = new String[]{
        "PLAIN", "BOLD", "ITALIC", "BOLD ITALIC"
    };
    final int[] fontStyleValues = new int[]{
        Font.PLAIN, Font.BOLD, Font.ITALIC, Font.BOLD + Font.ITALIC
    };

    final int[] fontSizeValues = new int[]{
        8, 9, 10, 11, 12, 14, 16, 18, 20, 22, 24, 26, 28, 36, 48, 72
    };

    /**
     * Creates new form FontChooser
     */
    public FontChooser() {
        GraphicsEnvironment env = GraphicsEnvironment
          .getLocalGraphicsEnvironment();
        fontFamilyNames = env.getAvailableFontFamilyNames();
        initComponents();
        fontNameList.setModel(new AbstractListModel() {

            @Override
            public int getSize() {
                return fontFamilyNames.length;
            }

            @Override
            public Object getElementAt(int index) {
                return fontFamilyNames[index];
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fontName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fontStyle = new javax.swing.JTextField();
        fontSize = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fontNameList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        fontStyleList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        fontSizeList = new javax.swing.JList();
        preview = new javax.swing.JLabel();

        jLabel1.setText("Font:");

        fontName.setEditable(false);
        fontName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fontName.setText("jTextField1");
        fontName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Font style:");

        fontStyle.setEditable(false);
        fontStyle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fontStyle.setText("PLAIN");

        fontSize.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        fontSize.setText("8");

        jLabel3.setText("Size:");

        fontNameList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        fontNameList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                fontNameListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(fontNameList);

        fontStyleList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Plain", "Bold", "Italic", "Bold Italic" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        fontStyleList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                fontStyleListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(fontStyleList);

        fontSizeList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "8", "9", "10", "11", "12", "14", "16", "18", "20", "22", "24", "26", "28", "36", "48", "72", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        fontSizeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                fontSizeListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(fontSizeList);

        preview.setBackground(new java.awt.Color(255, 255, 255));
        preview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preview.setText("PREVIEW");
        preview.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fontName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fontStyle)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(fontSize)))))
            .addComponent(preview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fontName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fontStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preview, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fontNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fontNameActionPerformed

    private void fontSizeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_fontSizeListValueChanged
        fontSize.setText(fontSizeList.getSelectedValue().toString());
        actualizePreview();
    }//GEN-LAST:event_fontSizeListValueChanged

    private void fontStyleListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_fontStyleListValueChanged
        fontStyle.setText(fontStylesNames[fontStyleList.getSelectedIndex()]);
        actualizePreview();
    }//GEN-LAST:event_fontStyleListValueChanged

    private void fontNameListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_fontNameListValueChanged
        fontName.setText((String) fontNameList.getSelectedValue());
        actualizePreview();
    }//GEN-LAST:event_fontNameListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fontName;
    private javax.swing.JList fontNameList;
    private javax.swing.JTextField fontSize;
    private javax.swing.JList fontSizeList;
    private javax.swing.JTextField fontStyle;
    private javax.swing.JList fontStyleList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel preview;
    // End of variables declaration//GEN-END:variables

    private void actualizePreview() {
        try {
            Font fnt = new Font(fontName.getText(), fontStyleValues[fontStyleList.getSelectedIndex()], Integer.parseInt(fontSize.getText()));
            preview.setFont(fnt);
        } catch (ArrayIndexOutOfBoundsException ex) {
        } catch (NumberFormatException ex) {

        }
    }

    void setValue(Font fnt) {
        for (int i = 0; i < fontFamilyNames.length; i++) {
            if (fontFamilyNames[i].equals(fnt.getFamily())) {
                fontNameList.setSelectedIndex(i);
            }
        }
        fontStyleList.setSelectedIndex(fnt.getStyle());
        for (int i = 0; i < fontSizeValues.length; i++) {
            if (fontSizeValues[i] == fnt.getSize()) {
                fontSizeList.setSelectedIndex(i);
            }
        }
    }

    Font getValue() {
        try {
            Font fnt = new Font(fontName.getText(), fontStyleValues[fontStyleList.getSelectedIndex()], Integer.parseInt(fontSize.getText()));
            return fnt;
        } catch (NumberFormatException ex) {
            return new Font(fontName.getText(), fontStyleValues[fontStyleList.getSelectedIndex()], 8);
        }
    }
}
