/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.vrany.chatbot;

import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 * Panel obsahuje nastaveni panelu
 *
 * @author michal
 */
public class OBSPanel extends javax.swing.JPanel {

    OBS obs;

    /**
     * Creates new form OBSPanel
     */
    public OBSPanel() {
        initComponents();
        obs = new OBS(400, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        backRed = new javax.swing.JSlider();
        backGreen = new javax.swing.JSlider();
        backBlue = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        width = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        height = new javax.swing.JSlider();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        sysRed = new javax.swing.JSlider();
        sysGreen = new javax.swing.JSlider();
        sysBlue = new javax.swing.JSlider();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        fontRed = new javax.swing.JSlider();
        fontGreen = new javax.swing.JSlider();
        fontBlue = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        preview = new javax.swing.JLabel();
        previewCheckbox = new javax.swing.JCheckBox();
        timestamps = new javax.swing.JCheckBox();
        shorterTimestamps = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        catchRed = new javax.swing.JSlider();
        catchGreen = new javax.swing.JSlider();
        catchBlue = new javax.swing.JSlider();

        jLabel10.setText("Background color");

        jButton4.setText("Set");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        backRed.setMaximum(255);
        backRed.setPreferredSize(new java.awt.Dimension(60, 23));
        backRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                backRedbackColorChanged(evt);
            }
        });
        jPanel2.add(backRed);

        backGreen.setMaximum(255);
        backGreen.setPreferredSize(new java.awt.Dimension(60, 23));
        backGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                backGreenbackColorChanged(evt);
            }
        });
        jPanel2.add(backGreen);

        backBlue.setMaximum(255);
        backBlue.setPreferredSize(new java.awt.Dimension(60, 23));
        backBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                backBluebackColorChanged(evt);
            }
        });
        jPanel2.add(backBlue);

        jLabel5.setText("Width");

        width.setMaximum(800);
        width.setMinimum(200);
        width.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                widthStateChanged(evt);
            }
        });

        jLabel6.setText("Height");

        height.setMaximum(600);
        height.setMinimum(100);
        height.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heightStateChanged(evt);
            }
        });

        jLabel12.setText("System text color");

        jButton6.setText("Set");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);

        sysRed.setMaximum(255);
        sysRed.setPreferredSize(new java.awt.Dimension(60, 23));
        sysRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sysRedbackColorChanged(evt);
            }
        });
        jPanel4.add(sysRed);

        sysGreen.setMaximum(255);
        sysGreen.setPreferredSize(new java.awt.Dimension(60, 23));
        sysGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sysGreenbackColorChanged(evt);
            }
        });
        jPanel4.add(sysGreen);

        sysBlue.setMaximum(255);
        sysBlue.setPreferredSize(new java.awt.Dimension(60, 23));
        sysBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sysBluebackColorChanged(evt);
            }
        });
        jPanel4.add(sysBlue);

        jLabel13.setText("Font text color");

        jButton7.setText("Set");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);

        fontRed.setMaximum(255);
        fontRed.setPreferredSize(new java.awt.Dimension(60, 23));
        fontRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fontRedbackColorChanged(evt);
            }
        });
        jPanel5.add(fontRed);

        fontGreen.setMaximum(255);
        fontGreen.setPreferredSize(new java.awt.Dimension(60, 23));
        fontGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fontGreenbackColorChanged(evt);
            }
        });
        jPanel5.add(fontGreen);

        fontBlue.setMaximum(255);
        fontBlue.setPreferredSize(new java.awt.Dimension(60, 23));
        fontBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fontBluebackColorChanged(evt);
            }
        });
        jPanel5.add(fontBlue);

        jLabel7.setText("Select font:");

        jButton1.setText("Choose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        preview.setBackground(new java.awt.Color(255, 255, 255));
        preview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preview.setText("PREVIEW");
        preview.setOpaque(true);

        previewCheckbox.setText("Show Preview");
        previewCheckbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                previewCheckboxStateChanged(evt);
            }
        });

        timestamps.setText("Timestamps?");
        timestamps.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                timestampsStateChanged(evt);
            }
        });

        shorterTimestamps.setText("Shorter timestamps?");
        shorterTimestamps.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shorterTimestampsStateChanged(evt);
            }
        });

        jLabel14.setText("Catch phrases font color");

        jButton8.setText("Set");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8);

        catchRed.setMaximum(255);
        catchRed.setPreferredSize(new java.awt.Dimension(60, 23));
        catchRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                catchRedbackColorChanged(evt);
            }
        });
        jPanel6.add(catchRed);

        catchGreen.setMaximum(255);
        catchGreen.setPreferredSize(new java.awt.Dimension(60, 23));
        catchGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                catchGreenbackColorChanged(evt);
            }
        });
        jPanel6.add(catchGreen);

        catchBlue.setMaximum(255);
        catchBlue.setPreferredSize(new java.awt.Dimension(60, 23));
        catchBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                catchBluebackColorChanged(evt);
            }
        });
        jPanel6.add(catchBlue);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(530, 538, Short.MAX_VALUE))
            .addComponent(width, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(height, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previewCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timestamps)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shorterTimestamps))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(preview, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previewCheckbox)
                    .addComponent(timestamps)
                    .addComponent(shorterTimestamps))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Color color = new Color(backRed.getValue(), backGreen.getValue(), backBlue.getValue());
        if ((color = JColorChooser.showDialog(this, "Choose color directly", color)) != null) {
            backRed.setValue(color.getRed());
            backGreen.setValue(color.getGreen());
            backBlue.setValue(color.getBlue());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void backRedbackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_backRedbackColorChanged
        setBackgroundColor();
    }//GEN-LAST:event_backRedbackColorChanged

    private void backGreenbackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_backGreenbackColorChanged
        setBackgroundColor();
    }//GEN-LAST:event_backGreenbackColorChanged

    private void backBluebackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_backBluebackColorChanged
        setBackgroundColor();
    }//GEN-LAST:event_backBluebackColorChanged

    private void widthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_widthStateChanged
        obs.setWidth(width.getValue());
    }//GEN-LAST:event_widthStateChanged

    private void heightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_heightStateChanged
        obs.setHeight(height.getValue());
        Frame parent = JOptionPane.getFrameForComponent(this);
        obs.setLocation(parent.getX(), parent.getY() - obs.getHeight());
    }//GEN-LAST:event_heightStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Color color = new Color(sysRed.getValue(), sysGreen.getValue(), sysBlue.getValue());
        if ((color = JColorChooser.showDialog(this, "Choose color directly", color)) != null) {
            sysRed.setValue(color.getRed());
            sysGreen.setValue(color.getGreen());
            sysBlue.setValue(color.getBlue());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void sysRedbackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sysRedbackColorChanged
        setSystemColor();
    }//GEN-LAST:event_sysRedbackColorChanged

    private void sysGreenbackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sysGreenbackColorChanged
        setSystemColor();
    }//GEN-LAST:event_sysGreenbackColorChanged

    private void sysBluebackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sysBluebackColorChanged
        setSystemColor();
    }//GEN-LAST:event_sysBluebackColorChanged

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Color color = new Color(fontRed.getValue(), fontGreen.getValue(), fontBlue.getValue());
        if ((color = JColorChooser.showDialog(this, "Choose color directly", color)) != null) {
            fontRed.setValue(color.getRed());
            fontGreen.setValue(color.getGreen());
            fontBlue.setValue(color.getBlue());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void fontRedbackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fontRedbackColorChanged
        setFontColor();
    }//GEN-LAST:event_fontRedbackColorChanged

    private void fontGreenbackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fontGreenbackColorChanged
        setFontColor();
    }//GEN-LAST:event_fontGreenbackColorChanged

    private void fontBluebackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fontBluebackColorChanged
        setFontColor();
    }//GEN-LAST:event_fontBluebackColorChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FontChooserDialog dlg = new FontChooserDialog(JOptionPane.getFrameForComponent(this), true);
        dlg.setValue(obs.ps.messageFont);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
        if (dlg.okPressed) {
            obs.setMessageFont(dlg.getValue());
            preview.setFont(obs.ps.messageFont);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void previewCheckboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_previewCheckboxStateChanged
        Frame parent = JOptionPane.getFrameForComponent(this);
        obs.setLocation(parent.getX(), parent.getY() - obs.getHeight());
        obs.setVisible(previewCheckbox.isSelected());
    }//GEN-LAST:event_previewCheckboxStateChanged

    private void timestampsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_timestampsStateChanged
        obs.ps.timeStampOn = timestamps.isSelected();
        obs.paint();
    }//GEN-LAST:event_timestampsStateChanged

    private void shorterTimestampsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_shorterTimestampsStateChanged
        obs.ps.shorterTimeStamp = shorterTimestamps.isSelected();
        obs.paint();
    }//GEN-LAST:event_shorterTimestampsStateChanged

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Color color = new Color(catchRed.getValue(), catchGreen.getValue(), catchBlue.getValue());
        if ((color = JColorChooser.showDialog(this, "Choose color directly", color)) != null) {
            catchRed.setValue(color.getRed());
            catchGreen.setValue(color.getGreen());
            catchBlue.setValue(color.getBlue());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void catchRedbackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_catchRedbackColorChanged
        setCatchColor();
    }//GEN-LAST:event_catchRedbackColorChanged

    private void catchGreenbackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_catchGreenbackColorChanged
        setCatchColor();
    }//GEN-LAST:event_catchGreenbackColorChanged

    private void catchBluebackColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_catchBluebackColorChanged
        setCatchColor();
    }//GEN-LAST:event_catchBluebackColorChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider backBlue;
    private javax.swing.JSlider backGreen;
    private javax.swing.JSlider backRed;
    private javax.swing.JSlider catchBlue;
    private javax.swing.JSlider catchGreen;
    private javax.swing.JSlider catchRed;
    private javax.swing.JSlider fontBlue;
    private javax.swing.JSlider fontGreen;
    private javax.swing.JSlider fontRed;
    private javax.swing.JSlider height;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel preview;
    private javax.swing.JCheckBox previewCheckbox;
    private javax.swing.JCheckBox shorterTimestamps;
    private javax.swing.JSlider sysBlue;
    private javax.swing.JSlider sysGreen;
    private javax.swing.JSlider sysRed;
    private javax.swing.JCheckBox timestamps;
    private javax.swing.JSlider width;
    // End of variables declaration//GEN-END:variables

    void loadSettings(IniFile settings) {
        String inp;
        inp = settings.getKeyValue("OBS", "backRed", "192");
        try {
            backRed.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("OBS", "backGreen", "192");
        try {
            backGreen.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("OBS", "backBlue", "192");
        try {
            backBlue.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("OBS", "width", "400");
        try {
            width.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("OBS", "height", "300");
        try {
            height.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("OBS", "sysRed", "255");
        try {
            sysRed.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("OBS", "sysGreen", "255");
        try {
            sysGreen.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("OBS", "sysBlue", "0");
        try {
            sysBlue.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("OBS", "fontRed", "255");
        try {
            fontRed.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("OBS", "fontGreen", "255");
        try {
            fontGreen.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("OBS", "fontBlue", "0");
        try {
            fontBlue.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        String fontFamily = settings.getKeyValue("OBS", "fontFamily", "Tahoma");
        int style = Font.PLAIN;
        inp = settings.getKeyValue("OBS", "fontStyle", "0");
        try {
            style = Integer.parseInt(inp);
        } catch (NumberFormatException ex) {
        }
        int size = 11;
        inp = settings.getKeyValue("OBS", "fontSize", "11");
        try {
            size = Integer.parseInt(inp);
        } catch (NumberFormatException ex) {
        }
        obs.setMessageFont(new Font(fontFamily, style, size));
        preview.setFont(obs.ps.messageFont);
        inp = settings.getKeyValue("OBS", "timestamps", "true");
        timestamps.setSelected(Boolean.parseBoolean(inp));
        obs.ps.timeStampOn = timestamps.isSelected();
        inp = settings.getKeyValue("OBS", "shorterTimestamps", "true");
        shorterTimestamps.setSelected(Boolean.parseBoolean(inp));
        obs.ps.shorterTimeStamp = shorterTimestamps.isSelected();
        inp = settings.getKeyValue("OBS", "catchRed", "255");
        try {
            catchRed.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("OBS", "catchGreen", "255");
        try {
            catchGreen.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
        inp = settings.getKeyValue("OBS", "catchBlue", "0");
        try {
            catchBlue.setValue(Integer.parseInt(inp));
        } catch (NumberFormatException ex) {
        }
    }

    void saveSettings(IniFile settings) {
        settings.setValue("OBS", "width", String.valueOf(obs.getWidth()));
        settings.setValue("OBS", "height", String.valueOf(obs.getHeight()));
        settings.setValue("OBS", "backRed", String.valueOf(backRed.getValue()));
        settings.setValue("OBS", "backGreen", String.valueOf(backGreen.getValue()));
        settings.setValue("OBS", "backBlue", String.valueOf(backBlue.getValue()));
        settings.setValue("OBS", "sysRed", String.valueOf(sysRed.getValue()));
        settings.setValue("OBS", "sysGreen", String.valueOf(sysGreen.getValue()));
        settings.setValue("OBS", "sysBlue", String.valueOf(sysBlue.getValue()));
        settings.setValue("OBS", "fontRed", String.valueOf(fontRed.getValue()));
        settings.setValue("OBS", "fontGreen", String.valueOf(fontGreen.getValue()));
        settings.setValue("OBS", "fontBlue", String.valueOf(fontBlue.getValue()));
        settings.setValue("OBS", "fontFamily", obs.ps.messageFont.getFamily());
        settings.setValue("OBS", "fontStyle", String.valueOf(obs.ps.messageFont.getStyle()));
        settings.setValue("OBS", "fontSize", String.valueOf(obs.ps.messageFont.getSize()));
        settings.setValue("OBS", "timestamps", String.valueOf(timestamps.isSelected()));
        settings.setValue("OBS", "shorterTimestamps", String.valueOf(shorterTimestamps.isSelected()));
        settings.setValue("OBS", "catchRed", String.valueOf(catchRed.getValue()));
        settings.setValue("OBS", "catchGreen", String.valueOf(catchGreen.getValue()));
        settings.setValue("OBS", "catchBlue", String.valueOf(catchBlue.getValue()));
    }

    public void onMessage(boolean hosted, boolean catchPhrase, User user, String message) {
        obs.addMessage(hosted, catchPhrase, user, message);
    }

    private void setBackgroundColor() {
        Color color = new Color(backRed.getValue(), backGreen.getValue(), backBlue.getValue());
        obs.setImageBackground(color);
    }

    private void setSystemColor() {
        Color color = new Color(sysRed.getValue(), sysGreen.getValue(), sysBlue.getValue());
        obs.setSystemColor(color);
        obs.paint();
    }

    private void setFontColor() {
        Color color = new Color(fontRed.getValue(), fontGreen.getValue(), fontBlue.getValue());
        obs.setFontColor(color);
        obs.paint();
    }

    private void setCatchColor() {
        Color color = new Color(catchRed.getValue(), catchGreen.getValue(), catchBlue.getValue());
        obs.setCatchColor(color);
        obs.repaint();
    }

}
